---
title: "Project Simple Run"
author: "Paul Hwang"
date: "2023-03-29"
output: html_document
---


```{r}
library(dplyr)
library(data.table)
library(ggplot2)
```


```{r}
sw <- fread("/Users/paulhwang/Desktop/Distributed Computing/Project1/MetricData.csv")
```

```{r}
sw1 <- sw %>% select(ID, Num_kudos, Num_bookmarks, Num_hits) %>% mutate(kudoperhit = Num_kudos/Num_hits, bmperhit = Num_bookmarks/Num_hits)
```

## Data Explorationg

### 1-D

```{r}
quantile(sw1$Num_hits, 0.25)
quantile(sw1$Num_hits, 0.75)

for (i in 1:9){
  print(quantile(sw1$Num_hits, i/10))
}

max(sw1$Num_hits)

mean(sw1$Num_hits)
```


```{r, warning=FALSE, comment=FALSE}
## Number of hits
ggplot(data=sw1, aes(x=Num_hits)) + geom_histogram() + 
  labs(title = "Distribution of Hits", x = "Hits")

ggplot(data=sw1, aes(x=Num_hits)) + geom_histogram() + scale_x_log10() +
  labs(title = "Log Distribution of Hits", x = "Hits")

ggplot(data=sw1, aes(x=Num_hits)) + geom_histogram() + scale_x_log10() + scale_y_log10() +
  labs(title = "Log Distribution of Hits", x = "Hits")
```

```{r}
quantile(sw1$Num_hits, 0.75)
```


```{r, warning=FALSE, comment=FALSE}
## Number of kudos
ggplot(data=sw1, aes(x=Num_kudos)) + geom_histogram() + 
  labs(title = "Distribution of Kudos", x = "Kudos")

ggplot(data=sw1, aes(x=Num_kudos)) + geom_histogram() + scale_x_log10() +
  labs(title = "Log Distribution of Kudos", x = "Kudos")
  
ggplot(data=sw1, aes(x=Num_kudos)) + geom_histogram() + scale_x_log10() + scale_y_log10() +
  labs(title = "Log-Log Distribution of Kudos", x = "Kudos")
```


```{r, warning=FALSE, comment=FALSE}
## Number of bookmarks
ggplot(data=sw1, aes(x=Num_bookmarks)) + geom_histogram() + 
  labs(title = "Distribution of Bookmarks", x = "Bookmarks")

ggplot(data=sw1, aes(x=Num_bookmarks)) + geom_histogram() + scale_x_log10() +
  labs(title = "Log Distribution of Bookmarks", x = "Bookmarks")
  
ggplot(data=sw1, aes(x=Num_bookmarks)) + geom_histogram() + scale_x_log10() + scale_y_log10() +
  labs(title = "Log-Log Distribution of Bookmarks", x = "Bookmarks")
```

### 2-D

```{r, warning=FALSE, comment=FALSE}
## Hits and kudos
ggplot(data = sw1, aes(x=Num_kudos, y=Num_hits)) + geom_point(alpha = 0.2) + 
  geom_smooth() + labs(title = "Scatterplot of Hits and Kudos", x = "Kudos", y = "Hits")

ggplot(data = sw1, aes(x=Num_kudos, y=Num_hits)) + geom_point(alpha = 0.2) + 
  geom_smooth(method = "lm", col = "red") + geom_smooth() + 
  scale_y_log10() + scale_x_log10() + 
  labs(title = "Scatterplot of Log Hits and Log Kudos", x = "Kudos", y = "Hits")
```

```{r, warning=FALSE, comment=FALSE}
## Hits and bookmarks
ggplot(data = sw1, aes(x=Num_bookmarks, y=Num_hits)) + geom_point(alpha = 0.2) + 
  geom_smooth() + labs(title = "Scatterplot of Hits and Bookmarls", x = "Bookmarks", y = "Hits")

ggplot(data = sw1, aes(x=Num_bookmarks, y=Num_hits)) + geom_point(alpha = 0.2) + 
  geom_smooth(method = "lm", col = "red") + geom_smooth() + 
  scale_y_log10() + scale_x_log10() + 
  labs(title = "Scatterplot of Log Hits and Log Bookmarks", x = "Bookmarks", y = "Hits")
```



```{r, eval = FALSE, echo = FALSE}
ggplot(data=sw1, aes(x=Num_hits)) + geom_histogram() + scale_x_log10()
ggplot(data=sw1, aes(x=Num_kudos)) + geom_histogram() + scale_x_log10()

ggplot(data = sw1, aes(x=Num_kudos, y=Num_hits)) + geom_point(alpha = 0.2) + 
  geom_smooth() + geom_abline(slope = 10, intercept = 0, col = "red") + scale_y_log10() +
  scale_x_log10()
ggplot(data = sw1, aes(x=Num_kudos, y=Num_hits)) + 
  geom_point(alpha = 0.2, shape = 21, fill = "lightblue", col = "black") +
  coord_cartesian(xlim = c(0,2000), ylim = c(0, 50000)) + 
  geom_abline(slope = 20, intercept = 0, col = "red")

ggplot(data=sw1, aes(x=kudoperhit)) + geom_histogram()
```

```{r, eval = FALSE, echo = FALSE}
ggplot(data=sw1, aes(x=Num_bookmarks)) + geom_histogram() + scale_x_log10() + scale_y_log10()


ggplot(data = sw1, aes(x=Num_bookmarks, y=Num_hits)) + geom_point(alpha = 0.2) + geom_smooth() + scale_x_log10()
ggplot(data = sw1, aes(x=Num_bookmarks, y=Num_hits)) + 
  geom_point(alpha = 0.2, shape = 21, fill = "lightblue", col = "black") +
  coord_cartesian(xlim = c(0,500), ylim = c(0, 50000)) + 
  geom_abline(slope = 10, intercept = 0, col = "red")
ggplot(data=sw1, aes(x=bmperhit)) + geom_histogram()
```

```{r, eval = FALSE, echo = FALSE}
sw2 = sw1 %>% filter(kudoperhit > 0.1)
sw3 = sw1 %>% filter(kudoperhit > 0.05)

dim(sw1)
dim(sw2)
dim(sw3)


```

### Random Exploration


```{r, eval = FALSE, echo = FALSE}

ggplot(sw2, aes(x=Num_hits)) + geom_histogram()
ggplot(sw2, aes(x=Num_kudos)) + geom_histogram()
ggplot(sw2, aes(x=Num_bookmarks)) + geom_histogram()


ggplot(sw2, aes(x=kudoperhit)) + geom_histogram()

ggplot(data = sw2, aes(x=Num_kudos, y=Num_hits)) + geom_point(alpha = 0.2) + 
  geom_smooth() + geom_abline(slope = 10, intercept = 0, col = "red")
ggplot(data = sw2, aes(x=Num_kudos, y=Num_hits)) + 
  geom_point(alpha = 0.2, shape = 21, fill = "lightblue", col = "black") +
  coord_cartesian(xlim = c(0,500), ylim = c(0, 5000)) + 
  geom_abline(slope = 10, intercept = 0, col = "red") + geom_smooth(method = "lm")

ggplot(data = sw3, aes(x=Num_kudos, y=Num_hits)) + geom_point(alpha = 0.2) + 
  geom_smooth() + geom_abline(slope = 10, intercept = 0, col = "red")
ggplot(data = sw3, aes(x=Num_kudos, y=Num_hits)) + 
  geom_point(alpha = 0.2, shape = 21, fill = "lightblue", col = "black") +
  coord_cartesian(xlim = c(0,1000), ylim = c(0, 10000)) + 
  geom_abline(slope = 10, intercept = 0, col = "red") + geom_smooth(method = "lm")




ggplot(sw2, aes(x=bmperhit)) + geom_histogram()


ggplot(data = sw2, aes(x=Num_bookmarks, y=Num_hits)) + geom_point(alpha = 0.2) + geom_smooth()
ggplot(data = sw2, aes(x=Num_bookmarks, y=Num_hits)) + 
  geom_point(alpha = 0.2, shape = 21, fill = "lightblue", col = "black") +
  coord_cartesian(xlim = c(0,50), ylim = c(0, 5000)) + 
  geom_abline(slope = 10, intercept = 0, col = "red") + geom_smooth(method = "lm") +
  geom_abline(slope = 40, intercept = 0, col = "green")
ggplot(data=sw1, aes(x=bmperhit)) + geom_histogram()


ggplot(data = sw3, aes(x=Num_bookmarks, y=Num_hits)) + geom_point(alpha = 0.2) + geom_smooth()
ggplot(data = sw3, aes(x=Num_bookmarks, y=Num_hits)) + 
  geom_point(alpha = 0.2, shape = 21, fill = "lightblue", col = "black") +
  coord_cartesian(xlim = c(0,200), ylim = c(0, 10000)) + 
  geom_abline(slope = 10, intercept = 0, col = "red") + geom_smooth(method = "lm") +
  geom_abline(slope = 40, intercept = 0, col = "green")
ggplot(data=sw1, aes(x=bmperhit)) + geom_histogram()
```

### Formatting

```{r}
names(sw)
```

```{r}

```


```{r}
popularity <- sw %>% select(Author, ID, Num_hits) %>% group_by(Author) %>% 
  summarize("MinRating" = min(Num_hits), "MaxRating" = max(Num_hits), 
         "MedRating" = median(Num_hits), "AvgRating" = mean(Num_hits))

popularity_log <- sw %>% mutate("LogPop" = log(Num_hits, base = 10)) %>% 
  select(Author, ID, LogPop) %>% mutate() %>% group_by(Author) %>% 
  summarize("MinRating" = min(LogPop), "MaxRating" = max(LogPop), 
         "MedRating" = median(LogPop), "AvgRating" = mean(LogPop))
```

```{r}
ggplot(data = popularity, aes(x=AvgRating)) + geom_histogram() +scale_x_log10()
ggplot(data = popularity, aes(x=MedRating)) + geom_histogram() +scale_x_log10()
ggplot(data = popularity, aes(x=MinRating)) + geom_histogram() +scale_x_log10()
ggplot(data = popularity, aes(x=MaxRating)) + geom_histogram() +scale_x_log10()
```
```{r}
ggplot(data = popularity_log, aes(x=AvgRating)) + geom_histogram()
ggplot(data = popularity_log, aes(x=MedRating)) + geom_histogram()
ggplot(data = popularity_log, aes(x=MinRating)) + geom_histogram()
ggplot(data = popularity_log, aes(x=MaxRating)) + geom_histogram()


ggplot() + geom_density(data = popularity_log, aes(x=AvgRating), col = "blue") +
  geom_density(data = popularity_log, aes(x=MedRating), col = "red") +
  geom_density(data = popularity_log, aes(x=MinRating), col = "green") +
  geom_density(data = popularity_log, aes(x=MaxRating), col = "black")
```

```{r}
write.csv(popularity, "/Users/paulhwang/Desktop/Distributed Computing/Project1/Metric.csv", 
          row.names = FALSE)

write.csv(popularity_log, "/Users/paulhwang/Desktop/Distributed Computing/Project1/LogMetric.csv", 
          row.names = FALSE)
```


## Looking at predictions of catboost

```{r}
res <- fread("/Users/paulhwang/Desktop/Distributed Computing/Project1/predictions.csv")
```

```{r}
names(res)
```


```{r}
quantile(res$pred_rating, 0.75)
```


```{r}
pt1 <- res %>% select(total_posts, avg_posts_year, avg_word_count, 
               avg_paragraph_count, pred_rating) %>% 
  group_by(total_posts) %>% 
  summarize("rating_beh" = mean(pred_rating))

pt2 <- res %>% select(total_posts, avg_posts_year, avg_word_count, 
               avg_paragraph_count, pred_rating) %>% 
  group_by(avg_posts_year) %>% 
  summarize("rating_beh" = mean(pred_rating))

pt3 <- res %>% select(total_posts, avg_posts_year, avg_word_count, 
               avg_paragraph_count, pred_rating) %>% 
  group_by(avg_word_count) %>% 
  summarize("rating_beh" = mean(pred_rating))

pt4 <- res %>% select(total_posts, avg_posts_year, avg_word_count, 
               avg_paragraph_count, pred_rating) %>% 
  group_by(avg_paragraph_count) %>% 
  summarize("rating_beh" = mean(pred_rating))
```

```{r}
pt1
pt2
pt3
pt4
```


```{r}
ggplot(data = pt1, aes(x=total_posts, y=rating_beh)) + geom_point() + scale_x_log10()
ggplot(data = pt2, aes(x=avg_posts_year, y=rating_beh)) + geom_point() + scale_x_log10()
ggplot(data = pt3, aes(x=avg_word_count, y=rating_beh)) + geom_point() + scale_x_log10()
ggplot(data = pt4, aes(x=avg_paragraph_count, y=rating_beh)) + geom_point() + scale_x_log10()
```



```{r}
d211 <- res %>% select(avg_posts_year, avg_word_count, 
               avg_paragraph_count, pred_rating) %>% 
  group_by(avg_posts_year, avg_word_count) %>% 
  summarise("rating_beh" = mean(pred_rating)) %>%
  mutate(across(c(1),factor))

d212 <- res %>% select(avg_posts_year, avg_word_count, 
               avg_paragraph_count, pred_rating) %>% 
  group_by(avg_posts_year, avg_word_count) %>% 
  summarise("rating_beh" = mean(pred_rating)) %>%
  mutate(across(c(2),factor))

d221 <- res %>% select(avg_posts_year, avg_word_count, 
               avg_paragraph_count, pred_rating) %>% 
  group_by(avg_posts_year, avg_paragraph_count) %>% 
  summarise("rating_beh" = mean(pred_rating)) %>%
  mutate(across(c(1),factor))

d222 <- res %>% select(avg_posts_year, avg_word_count, 
               avg_paragraph_count, pred_rating) %>% 
  group_by(avg_posts_year, avg_paragraph_count) %>% 
  summarise("rating_beh" = mean(pred_rating)) %>%
  mutate(across(c(2),factor))

d231 <- res %>% select(avg_posts_year, avg_word_count, 
               avg_paragraph_count, pred_rating) %>% 
  group_by(avg_word_count, avg_paragraph_count) %>% 
  summarise("rating_beh" = mean(pred_rating)) %>%
  mutate(across(c(1),factor))

d232 <- res %>% select(avg_posts_year, avg_word_count, 
               avg_paragraph_count, pred_rating) %>% 
  group_by(avg_word_count, avg_paragraph_count) %>% 
  summarise("rating_beh" = mean(pred_rating)) %>%
  mutate(across(c(2),factor))
```

```{r}
d212
d222
d232
```

```{r}
ggplot(data = d211, aes(x=avg_word_count, y= rating_beh, col = avg_posts_year)) +
  geom_point()

ggplot(data = d212, aes(x=avg_posts_year, y= rating_beh, col = avg_word_count)) +
  geom_point()

ggplot(data = d221, aes(x=avg_paragraph_count, y= rating_beh, col = avg_posts_year)) +
  geom_point()

ggplot(data = d222, aes(x=avg_posts_year, y= rating_beh, col = avg_paragraph_count)) +
  geom_point()

ggplot(data = d231, aes(x=avg_word_count, y= rating_beh, col = avg_paragraph_count)) +
  geom_point()

ggplot(data = d232, aes(x=avg_paragraph_count, y= rating_beh, col = avg_word_count)) +
  geom_point()
```

## outlier removed

```{r}
res_rm <- fread("/Users/paulhwang/Desktop/Distributed Computing/Project1/predictions_rm.csv")
```

```{r}
pt1 <- res_rm %>% select(total_posts, avg_posts_year, avg_word_count, 
               avg_paragraph_count, pred_rating) %>% 
  group_by(total_posts) %>% 
  summarize("rating_beh" = mean(pred_rating))

pt2 <- res_rm %>% select(total_posts, avg_posts_year, avg_word_count, 
               avg_paragraph_count, pred_rating) %>% 
  group_by(avg_posts_year) %>% 
  summarize("rating_beh" = mean(pred_rating))

pt3 <- res_rm %>% select(total_posts, avg_posts_year, avg_word_count, 
               avg_paragraph_count, pred_rating) %>% 
  group_by(avg_word_count) %>% 
  summarize("rating_beh" = mean(pred_rating))

pt4 <- res_rm %>% select(total_posts, avg_posts_year, avg_word_count, 
               avg_paragraph_count, pred_rating) %>% 
  group_by(avg_paragraph_count) %>% 
  summarize("rating_beh" = mean(pred_rating))
```

```{r}
pt1
pt2
pt3
pt4
```

```{r}
d211 <- res_rm %>% select(avg_posts_year, avg_word_count, 
               avg_paragraph_count, pred_rating) %>% 
  group_by(avg_posts_year, avg_word_count) %>% 
  summarise("rating_beh" = mean(pred_rating)) %>%
  mutate(across(c(1),factor))

d212 <- res_rm %>% select(avg_posts_year, avg_word_count, 
               avg_paragraph_count, pred_rating) %>% 
  group_by(avg_posts_year, avg_word_count) %>% 
  summarise("rating_beh" = mean(pred_rating)) %>%
  mutate(across(c(2),factor))

d221 <- res_rm %>% select(avg_posts_year, avg_word_count, 
               avg_paragraph_count, pred_rating) %>% 
  group_by(avg_posts_year, avg_paragraph_count) %>% 
  summarise("rating_beh" = mean(pred_rating)) %>%
  mutate(across(c(1),factor))

d222 <- res_rm %>% select(avg_posts_year, avg_word_count, 
               avg_paragraph_count, pred_rating) %>% 
  group_by(avg_posts_year, avg_paragraph_count) %>% 
  summarise("rating_beh" = mean(pred_rating)) %>%
  mutate(across(c(2),factor))

d231 <- res_rm %>% select(avg_posts_year, avg_word_count, 
               avg_paragraph_count, pred_rating) %>% 
  group_by(avg_word_count, avg_paragraph_count) %>% 
  summarise("rating_beh" = mean(pred_rating)) %>%
  mutate(across(c(1),factor))

d232 <- res_rm %>% select(avg_posts_year, avg_word_count, 
               avg_paragraph_count, pred_rating) %>% 
  group_by(avg_word_count, avg_paragraph_count) %>% 
  summarise("rating_beh" = mean(pred_rating)) %>%
  mutate(across(c(2),factor))
```

```{r}
d212
d222
d232
```

```{r}
ggplot(data = d211, aes(x=avg_word_count, y= rating_beh, col = avg_posts_year)) +
  geom_point()

ggplot(data = d212, aes(x=avg_posts_year, y= rating_beh, col = avg_word_count)) +
  geom_point()

ggplot(data = d221, aes(x=avg_paragraph_count, y= rating_beh, col = avg_posts_year)) +
  geom_point()

ggplot(data = d222, aes(x=avg_posts_year, y= rating_beh, col = avg_paragraph_count)) +
  geom_point()

ggplot(data = d231, aes(x=avg_word_count, y= rating_beh, col = avg_paragraph_count)) +
  geom_point()

ggplot(data = d232, aes(x=avg_paragraph_count, y= rating_beh, col = avg_word_count)) +
  geom_point()
```
